export const SAVE_DAYSALE_REQUEST = 'SAVE_DAYSALE_REQUEST';
export const SAVE_DAYSALE_SUCCESS = 'SAVE_DAYSALE_SUCESSS';
export const SAVE_DAYSALE_FAIL = 'SAVE_DAYSALE_FAIL';
export const SAVE_DAYSALE_RESET = 'SAVE_DAYSALE_RESET';

export const MONTH_TOTAL_REQUEST = 'MONTH_TOTAL_REQUEST';
export const MONTH_TOTAL_SUCCESS = 'MONTH_TOTAL_SUCESSS';
export const MONTH_TOTAL_FAIL = 'MONTH_TOTAL_FAIL';
export const MONTH_TOTAL_RESET = 'MONTH_TOTAL_RESET';
